name                = "temporary-mail"
main                = "worker.js"
compatibility_date  = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
MAIL_DOMAIN = "mediasaya.web.id"

[[kv_namespaces]]
binding = "MAIL_KV"
id      = "366e8c8e0a7941f8983d8fef35983109"
